### ISSUE TITLE
make DAGService interface compatible with levelup 

### ISSUE THREAD

**Issue by wanderer** [ipld/js-ipld-dag-pb#2]
Can we make DAGService interface compatible with levelup? 
The idea here is that we can swap backends if needed. 
To have compatibility rename
`remove -> del`
`getRecursiveStream -> createReadStream`

**Comment by diasdavid** [comment]
Hi @wanderer :) Yes, it can, in fact, it already almost is"*" is, DAGService uses BlockService and Block Services uses the IPFS Repo (node -> block -> bytes).

"*" I say almost, because it was before we migrated to pull-streams, now we just need to create an interface on top of levelup that knows about pull-streams.

**Comment by diasdavid** [comment]
Hope this is clear now, let me know if it isn't. Closing now.

**Comment by dignifiedquire** [comment]
@diasdavid there is pull-level: http://npmjs.com/pull-level

**Comment by diasdavid** [comment]
@dignifiedquire I believe the confusion was if it was this the place to attach to a level store. The answer was: that happens on the ipfs-repo module.
